
tasks:
  - name: install System
    before: |
      echo 'export PYTHON=/home/gitpod/.pyenv/shims/python' >> ~/.bashrc
      export PYTHON=/home/gitpod/.pyenv/shims/python
      sudo cp -f /workspace/robotframework-tutorial-de/.vscode/RF_BACKGROUND.png /usr/share/backgrounds/xfce/xfce-verticals.png
      npx --yes playwright install-deps
      exit
  - name: install Browser
    init: |
      export PYTHON=/home/gitpod/.pyenv/shims/python
      code -r .
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      rfbrowser init
      code -r ./Beratertag/Testfaelle/00_Intro/01_Test_Me.robot 
      exit

image: gitpod/workspace-full-vnc
ports:
  - port: 6080
    onOpen: open-preview
    visibility: private
vscode:
  extensions:
    - ms-python.python
    - d-biehl.robotcode
    - bierner.docs-view
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - PKief.material-icon-theme
    - mechatroner.rainbow-csv
