
tasks:
  - init: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      rfbrowser init
      npx --yes playwright install-deps
image: gitpod/workspace-full-vnc
ports:
  - port: 6080
    onOpen: open-preview
    visibility: private
vscode:
  extensions:
    - ms-python.python
    - d-biehl.robotcode
    - bierner.docs-view
    - ms-vscode.live-server
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers