
tasks:
  - name: install System
    before: |
      sudo cp -f /workspace/robocon-de-tutorial/.vscode/RF_BACKGROUND.png /usr/share/backgrounds/xfce/xfce-verticals.png
      npx --yes playwright install-deps
      exit
  - name: install Browser
    init: |
      code -r Participants/
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      rfbrowser init
      code -r .
      exit

image: gitpod/workspace-full-vnc
ports:
  - port: 6080
    onOpen: open-preview
    visibility: private
vscode:
  extensions:
    - ms-python.python
    - d-biehl.robotcode
    - bierner.docs-view
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - PKief.material-icon-theme
    - mechatroner.rainbow-csv
